export const TRAVEL_TIME_MIN_PER_KM = 2.5
export const TRAVEL_TIME_BUFFER_MIN = 5
export const ROUTE_PREVIEW_ATTRACTIONS_COUNT = 8
export const DEFAULT_DURATION_MINUTES = 90
export const ITINERARY_GENERATE_LIMIT = 5
export const ITINERARY_GENERATE_TTL_MS = 60000
