import React from 'react'
import { Link } from 'react-router-dom'
import { ROUTES } from '@/constants/routes'

export const TermsPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#08091a] text-gray-900 dark:text-gray-100 transition-colors duration-200">
      <nav className="max-w-4xl mx-auto px-6 py-6 flex justify-between items-center border-b border-gray-200 dark:border-gray-800">
        <Link to={ROUTES.HOME} className="flex items-center gap-2 font-bold text-lg">
          <span className="w-8 h-8 rounded bg-primary flex items-center justify-center text-white">R</span>
          Routiq
        </Link>
        <Link to={ROUTES.HOME} className="text-sm hover:text-primary transition-colors">
          Back to Home
        </Link>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-extrabold mb-8 bg-gradient-to-r from-blue-500 to-indigo-500 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <div className="space-y-6 text-gray-600 dark:text-gray-300 leading-relaxed">
          <p className="text-sm text-gray-400">Last updated: June 5, 2026</p>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">1. Agreement to Terms</h2>
            <p>
              By accessing or using Routiq, you agree to be bound by these Terms of Service. If you do not agree, 
              please do not access or use the application.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">2. Use of Service</h2>
            <p>
              You agree to use Routiq only for lawful purposes related to trip planning, group coordination, and itinerary viewing. 
              You must not use the service to scrape data, execute denial of service attacks, or abuse API rate limits.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">3. User Accounts</h2>
            <p>
              When creating an account, you must provide accurate registration details. You are responsible for keeping 
              your Supabase-managed authentication credentials secure. We reserve the right to suspend accounts displaying 
              malicious activity.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">4. Intellectually Property</h2>
            <p>
              The application, its interface design, styling, logo, and backend services are the intellectual property 
              of Routiq. User-generated content remains the property of the users, but by posting content in group environments, 
              you grant members permission to view and interact with that content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">5. AI Generated Material Disclaimer</h2>
            <p>
              Itineraries generated by Routiq are powered by third-party AI models (Google Gemini 2.5 Flash). We do not guarantee 
              the accuracy of the schedules, route feasibility, opening times, or safety of suggested attractions. 
              Always cross-reference generated plans with local conditions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">6. Limitation of Liability</h2>
            <p>
              Routiq and its developers shall not be liable for any damages, travel disruptions, missed flights, or accidents 
              occurring while executing travel plans designed with this service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">7. Governing Law</h2>
            <p>
              These terms are governed by the laws of the Republic of Slovenia, without regard to conflict of law principles.
            </p>
          </section>
        </div>
      </main>

      <footer className="max-w-4xl mx-auto px-6 py-8 text-center text-xs text-gray-500 border-t border-gray-200 dark:border-gray-800">
        &copy; 2026 Routiq. All rights reserved.
      </footer>
    </div>
  )
}
