import React from 'react'
import { LegalLayout } from './LegalLayout'

export const TermsPage: React.FC = () => {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="June 5, 2026">
      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">1. Agreement to Terms</h2>
        <p>
          By accessing or using Routiq, you agree to be bound by these Terms of Service. If you do not agree, 
          please do not access or use the application.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">2. Use of Service</h2>
        <p>
          You agree to use Routiq only for lawful purposes related to trip planning, group coordination, and itinerary viewing. 
          You must not use the service to scrape data, execute denial of service attacks, or abuse API rate limits.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">3. User Accounts</h2>
        <p>
          When creating an account, you must provide accurate registration details. You are responsible for keeping 
          your Supabase-managed authentication credentials secure. We reserve the right to suspend accounts displaying 
          malicious activity.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">4. Intellectually Property</h2>
        <p>
          The application, its interface design, styling, logo, and backend services are the intellectual property 
          of Routiq. User-generated content remains the property of the users, but by posting content in group environments, 
          you grant members permission to view and interact with that content.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">5. AI Generated Material Disclaimer</h2>
        <p>
          Itineraries generated by Routiq are powered by third-party AI models (Google Gemini 2.5 Flash). We do not guarantee 
          the accuracy of the schedules, route feasibility, opening times, or safety of suggested attractions. 
          Always cross-reference generated plans with local conditions.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">6. Limitation of Liability</h2>
        <p>
          Routiq and its developers shall not be liable for any damages, travel disruptions, missed flights, or accidents 
          occurring while executing travel plans designed with this service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white">7. Governing Law</h2>
        <p>
          These terms are governed by the laws of the Republic of Slovenia, without regard to conflict of law principles.
        </p>
      </section>
    </LegalLayout>
  )
}
